config/routes.rb
Rails.application.routes.draw do
  
  resources :articles do
    resources :comments
  end
  
  resources :comments
  
  root 'articles#index'
end

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def new
    end
    
    def create
        params.permit!
        @article = Article.new(params[:article])
        @article.save()
        
        redirect_to @article
    end
    
    def show
        @article = Article.find(params[:id])
    end
    
    def index
       @articles = Article.all 
    end
    
    def
        destroy
        article = Article.find(params[:id])
        article.destroy
        
        redirect_to articles_path
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        @article =Article.find(params[:id])
        @article.update(params.require(:article).permit(:title, :content))
        
        redirect_to @article
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        params.permit!
        @article = Article.find(params[:article_id])
        @comment = @article.comments.new(params[:comment])
        
        @comment.save
        redirect_to :back
    end
    
    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to :back
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</p>

<p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
</p>

<p><%= f.submit %></p>
<% end %>

app/views/articles/index.html.erb
<p>Titles</p>

<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
        
        <% @articles.each do |article| %>
        <tr>
            <td><%= article.title %></td>
            <td><%= article.content %></td>
            <td><%= link_to 'show', article_path(article) %></td>
        </tr>
        <% end %>
    </tr>
</table>

<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: '/articles/' do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>
    
    <p>
        <%= f.label :content %><br>
        <%= f.text_field :content %>
    </p>
    
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/articles/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @article.title %>
</p>
<p>
    <strong>Content: </strong>
    <%= @article.content %>
</p>
<br>
<%= link_to "수정", edit_article_path(@article) %>
<%= link_to "삭제", article_path(@article), method: :delete %>
<%= link_to "Articles list", articles_path %>

<p>
    <h3>&lt; Comments &gt;</h3>
    <ul id="comments">
        <% @article.comments.each do |comment| %>
        <%= comment.content %> 
        <%= link_to '삭제', comment_path(comment), :method => :delete, date: {confirm: "정말로 삭제하시겠습니까?"} %>
        <br>
        <% end %>
    </ul>
</p>

<p>
    <%= form_for :comment, url: article_comments_path(@article.id) do |f| %>
        <%= f.text_area :content %>
        <%= f.submit %>
        <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>